// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {recorder} from '../models';
import {config} from '../models';
import {history} from '../models';
import {main} from '../models';
import {metadata} from '../models';

export function AddRecordingHistory(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AddRecordingHistoryWithDetails(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<void>;

export function AddRecordingHistoryWithStatus(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<void>;

export function AddStreamer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CheckRecordingTools():Promise<recorder.ToolStatus>;

export function CheckRecordingToolsWithPaths(arg1:string,arg2:string):Promise<recorder.ToolStatus>;

export function ClearRecordingHistory():Promise<void>;

export function DeleteHistoryRecord(arg1:string):Promise<void>;

export function DeleteHistoryRecordAndFile(arg1:string):Promise<string>;

export function ExchangeOAuthCode(arg1:string):Promise<string>;

export function ForceQuit():Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetOAuthAuthorizeURL():Promise<string>;

export function GetRecordingHistory():Promise<Array<history.RecordingRecord>>;

export function GetRuntimeDiagnostics():Promise<main.RuntimeDiagnostics>;

export function GetStreamerDiagnostics(arg1:string):Promise<main.StreamerDiagnostics>;

export function GetStreamerMetadata(arg1:string):Promise<metadata.StreamerMetadata>;

export function GetStreamers():Promise<Array<main.StreamerStatus>>;

export function HideWindow():Promise<void>;

export function NotifyAppLog(arg1:string):Promise<void>;

export function NotifyStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenStreamerLogFolder(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RefreshStreamerMetadata(arg1:string):Promise<string>;

export function RemoveStreamer(arg1:string):Promise<string>;

export function RunHealthCheck():Promise<main.HealthCheckReport>;

export function RunHealthCheckWithSettings(arg1:main.SettingsPayload):Promise<main.HealthCheckReport>;

export function SaveSettings(arg1:main.SettingsPayload):Promise<string>;

export function SelectCookieFile():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SetAllMonitoring(arg1:boolean):Promise<void>;

export function SetMonitoring(arg1:string,arg2:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function TestTelegramNotification(arg1:config.TelegramConfig):Promise<string>;

export function ToggleMonitoring(arg1:string):Promise<boolean>;

export function UpdateHistoryRecordStatus(arg1:string,arg2:string):Promise<void>;

export function UpdateStreamerOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function VerifyOAuthToken():Promise<string>;
