// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecordingHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddRecordingHistory'](arg1, arg2, arg3, arg4);
}

export function AddRecordingHistoryWithDetails(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddRecordingHistoryWithDetails'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddRecordingHistoryWithStatus(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRecordingHistoryWithStatus'](arg1, arg2, arg3, arg4, arg5);
}

export function AddStreamer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddStreamer'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckRecordingTools() {
  return window['go']['main']['App']['CheckRecordingTools']();
}

export function CheckRecordingToolsWithPaths(arg1, arg2) {
  return window['go']['main']['App']['CheckRecordingToolsWithPaths'](arg1, arg2);
}

export function ClearRecordingHistory() {
  return window['go']['main']['App']['ClearRecordingHistory']();
}

export function DeleteHistoryRecord(arg1) {
  return window['go']['main']['App']['DeleteHistoryRecord'](arg1);
}

export function DeleteHistoryRecordAndFile(arg1) {
  return window['go']['main']['App']['DeleteHistoryRecordAndFile'](arg1);
}

export function ExchangeOAuthCode(arg1) {
  return window['go']['main']['App']['ExchangeOAuthCode'](arg1);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetOAuthAuthorizeURL() {
  return window['go']['main']['App']['GetOAuthAuthorizeURL']();
}

export function GetRecordingHistory() {
  return window['go']['main']['App']['GetRecordingHistory']();
}

export function GetRuntimeDiagnostics() {
  return window['go']['main']['App']['GetRuntimeDiagnostics']();
}

export function GetStreamerDiagnostics(arg1) {
  return window['go']['main']['App']['GetStreamerDiagnostics'](arg1);
}

export function GetStreamerMetadata(arg1) {
  return window['go']['main']['App']['GetStreamerMetadata'](arg1);
}

export function GetStreamers() {
  return window['go']['main']['App']['GetStreamers']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function NotifyAppLog(arg1) {
  return window['go']['main']['App']['NotifyAppLog'](arg1);
}

export function NotifyStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['NotifyStatus'](arg1, arg2, arg3);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenStreamerLogFolder(arg1) {
  return window['go']['main']['App']['OpenStreamerLogFolder'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshStreamerMetadata(arg1) {
  return window['go']['main']['App']['RefreshStreamerMetadata'](arg1);
}

export function RemoveStreamer(arg1) {
  return window['go']['main']['App']['RemoveStreamer'](arg1);
}

export function RunHealthCheck() {
  return window['go']['main']['App']['RunHealthCheck']();
}

export function RunHealthCheckWithSettings(arg1) {
  return window['go']['main']['App']['RunHealthCheckWithSettings'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectCookieFile() {
  return window['go']['main']['App']['SelectCookieFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetAllMonitoring(arg1) {
  return window['go']['main']['App']['SetAllMonitoring'](arg1);
}

export function SetMonitoring(arg1, arg2) {
  return window['go']['main']['App']['SetMonitoring'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function TestTelegramNotification(arg1) {
  return window['go']['main']['App']['TestTelegramNotification'](arg1);
}

export function ToggleMonitoring(arg1) {
  return window['go']['main']['App']['ToggleMonitoring'](arg1);
}

export function UpdateHistoryRecordStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateHistoryRecordStatus'](arg1, arg2);
}

export function UpdateStreamerOptions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateStreamerOptions'](arg1, arg2, arg3, arg4, arg5);
}

export function VerifyOAuthToken() {
  return window['go']['main']['App']['VerifyOAuthToken']();
}
